// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Object struct {
	Key          string
	Name         string
	Parent       string
	IsDir        bool
	Size         int64
	LastModified string
	ContentType  string
	Etag         string
}

type ObjectsFt struct {
	Name string
	Key  string
}
