// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getObject = `-- name: GetObject :one
SELECT size, content_type, last_modified, etag
FROM objects
WHERE key = ?
`

type GetObjectRow struct {
	Size         int64
	ContentType  string
	LastModified string
	Etag         string
}

func (q *Queries) GetObject(ctx context.Context, key string) (GetObjectRow, error) {
	row := q.db.QueryRowContext(ctx, getObject, key)
	var i GetObjectRow
	err := row.Scan(
		&i.Size,
		&i.ContentType,
		&i.LastModified,
		&i.Etag,
	)
	return i, err
}

const insertObject = `-- name: InsertObject :exec
INSERT INTO objects (
    key, name, parent, is_dir, size, last_modified, content_type, etag
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertObjectParams struct {
	Key          string
	Name         string
	Parent       string
	IsDir        bool
	Size         int64
	LastModified string
	ContentType  string
	Etag         string
}

func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) error {
	_, err := q.db.ExecContext(ctx, insertObject,
		arg.Key,
		arg.Name,
		arg.Parent,
		arg.IsDir,
		arg.Size,
		arg.LastModified,
		arg.ContentType,
		arg.Etag,
	)
	return err
}

const listObjectsByParent = `-- name: ListObjectsByParent :many
SELECT key, name, is_dir, size, last_modified
FROM objects
WHERE parent = ?
`

type ListObjectsByParentRow struct {
	Key          string
	Name         string
	IsDir        bool
	Size         int64
	LastModified string
}

func (q *Queries) ListObjectsByParent(ctx context.Context, parent string) ([]ListObjectsByParentRow, error) {
	rows, err := q.db.QueryContext(ctx, listObjectsByParent, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObjectsByParentRow
	for rows.Next() {
		var i ListObjectsByParentRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchObjects = `-- name: SearchObjects :many
SELECT o.key, o.name, o.is_dir, o.size, o.last_modified
FROM objects o
JOIN objects_fts f ON o.key = f.key
WHERE f.name MATCH ? LIMIT 600
`

type SearchObjectsRow struct {
	Key          string
	Name         string
	IsDir        bool
	Size         int64
	LastModified string
}

func (q *Queries) SearchObjects(ctx context.Context, name string) ([]SearchObjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchObjects, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchObjectsRow
	for rows.Next() {
		var i SearchObjectsRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.IsDir,
			&i.Size,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
